print('Please enter name:', end=' ')
name = input()
print('What is todays date?', end=' ')
date = input()
print('What is the assignment name?', end=' ')
assignment_name = input()
print('What is the description of the assignment?', end=' ')
brief_description = input()
print('Welcome', name)
print('Todays date is:', date)
print('Your current assignment is:', assignment_name)
print('Your project description for', assignment_name, 'is', brief_description)
